name: Build pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: build
        run: |
          ./gradlew build
